### ISSUE TITLE
(bug): iOS build failed (cannot convert value of type '(_) -> ()' to expected argument type 'CDVInvokedUrlCommand')

### ISSUE THREAD

**Issue by codi0** [EinfachHans/cordova-plugin-contacts-x#2]
# Bug Report

**Current Behavior:**
I'm trying to run a build using Xcode 11.3 and it fails with the following error message:

```
[21:45:48] /tmp/download/platforms/ios/testproject/Plugins/cordova-plugin-contacts-x/ContactsX.swift:19:32: error: cannot convert value of type '(_) -> ()' to expected argument type 'CDVInvokedUrlCommand'
[21:45:48]             self.hasPermission { (granted) in
[21:45:48]                                ^~~~~~~~~~~~~~
[21:45:48] /tmp/download/platforms/ios/testproject/Plugins/cordova-plugin-contacts-x/ContactsX.swift:74:28: error: cannot convert value of type '(_) -> ()' to expected argument type 'CDVInvokedUrlCommand'
[21:45:48]         self.hasPermission { (granted) in
```

**Environment information:**
Cordova CLI v10.0.0
cordova-ios v6.1.0
cordova-plugin-contacts-x v1.1.0
Monaca.io remote build tool (running Xcode 11.3)

Unfortunately I know next to nothing about Swift, so haven't been able to debug it myself. The best I could find online was a reference to Swift 3 code throwing similar errors in Xcode versions where Swift 4+ is required.

P.S. Thanks for creating the plugin. Has worked perfectly on Android and performs better than any of the alternatives.

**Comment by EinfachHans** [comment]
Please try to add `<preference name="UseSwiftLanguageVersion" value="5" />` to your **config.xml**.
After that remove the tmp folders (**plugins**, **platforms**) and build again

**Comment by codi0** [comment]
Thanks for the response. Tried as suggested (with otherwise exactly the same build settings as before), but unfortunately the same error occurred.

I then tried a completely default cordova project, with just this plugin added (again, same build settings). Whther the preference was omitted, or set to "4" or "5", exactly the same error each time. I can see it reference the correct language version (E.g. Use Swift language version 5), but the build error didn't change.

**Comment by EinfachHans** [comment]
Please send me a reproducable Repository

**Comment by codi0** [comment]
I've [shared a repo](https://github.com/codi0/contacts-x-test) with you that contains a cordova export from Monaca.io, which I used to run the bare-bones test build.

That was derived from a cordova project setup on Windows 10, using the latest Cordova CLI release. Added the contacts-x plugin on my local machine, then imported the project straight into Monaca (it adds a few things during the import to the config/package files). I then ran it's build process for iOS, using Cordova 10.0 and Xcode 11.3.

**Comment by EinfachHans** [comment]
please create a small reproducable repo. In the best case you create a new app, add only this plugin and check if it works. If not, post the link to that repo

**Comment by codi0** [comment]
Yes, that's what I shared in the previous post:

https://github.com/codi0/contacts-x-test

I am starting to think it may be specific to their remote build process somehow, but I can't verify by running it locally due to not having access to a Mac (and therefore having to rely on remote build for iOS).

**Comment by EinfachHans** [comment]
i can't reprodue that. Is there a reason why you are not on the latest xcode?

**Comment by Mickey34** [comment]
Hi,
I've got the same issue with xcode 11.3. Using xcode 12.3 solved the problem.
